### PR TITLE
Changed TimeField/TimeFormat to IndexField/IndexFormat

### PR DESCRIPTION
**Pull request by TinaUll**
Hi @osisoft-jcoffman please let me know if this works or if there's anything related to this that I need to change. Thank you!

### CODE REVIEW

**Review by osisoft-jcoffman — APPROVED** [review]
Hey Tina. This looks good! Thanks!

**Comment by osisoft-jcoffman** [comment]
I did notice that there are a couple of TimeField names on the "JSONPath syntax for value retrieval" page (https://docs.osisoft.com/bundle/pi-adapter-structured-data-files/page/main/shared-content/configuration/text-parser/jsonpath-syntax-for-value-retrieval.html), but I couldn't find that in page in the structured data files main documentation branch. Is this page in TextParser documentation?

**Comment by TinaUll** [comment]
@osisoft-jcoffman That text is indeed part of the TextParser documentation that is part of the Adapter framework documentation. Is it safe to update it there too?

**Comment by osisoft-jcoffman** [comment]
Hi @TinaUll, I would double check with the other text based adapters (MQTT and Azure Event Hub) to be sure before changing it. I think all text-based adapters should be using IndexField instead of TimeField, but it's better to be safe than sorry. Not changing this shouldn't hold up this PR though. Thanks!

**Pull request merged**
