### PR TITLE
Created discovery topic and added to toc.yml

### PR DESCRIPTION
**Pull request by TinaUll**
Hi @osisoft-jcoffman, I drafted the discovery topic for SDF adapter. What's missing is the query string with description of those items. The query rules need to be double-checked too. Feel free to update the topic as needed. Thank you!

### CODE REVIEW

**Comment by osisoft-jcoffman** [comment]
Hi @TinaUll,

As of right now, I don't think there are any query parameters that the SDF adapter will accept for discovery. There were a couple of query parameter options that were discussed, but none have come to fruition so far. That being said, this could change as we get feedback from the scheduled sprint review tomorrow.

**Comment by osisoft-jcoffman** [comment]
Hi @TinaUll, I've updated the discovery page with the necessary query string examples and parameters. Please feel free to update as needed. Also, I've updated the data-source.md and principles-of-operation.md files to include discovery-related content. These will probably need adjusting as you merge in with the existing main branch. Let me know if you have any questions. Thanks!

**Comment by TinaUll** [comment]
@osisoft-jcoffman I made some minor wording and formatting updates. Do you mind taking another look? If it looks good, I can merge. Thank you!

**Review by osisoft-jcoffman — APPROVED** [review]
Hey @TinaUll, your changes look good. Thanks!

**Pull request merged**
